// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhzaslnlwgxtnrtsyrtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoemFzbG5sd2d4dG5ydHN5cnR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MjEyMjMsImV4cCI6MjA2Mzk5NzIyM30.aB_GGfbsGF9qFDI2fw81Tf3ZRYDPuuJCPPG-N62YMGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);